### ISSUE TITLE
Problem when updating model 

### ISSUE THREAD

**Issue by dinoradulovic** [globalize/globalize-accessors#23]
This is how my form looks like:

<%= form_for([:admin, @category], remote: true) do |f| %>
  <% Category.globalize_attribute_names.each do |lang| %>
    <div class="field">
      <%= f.label lang %><br>
      <%= f.text_field lang %>
    </div>
  <% end %>

<div class="actions">
  <%= f.submit %>
</div>
<% end %>

everythig works fine when I`m creating a model. But when I try to edit it I get this error:

undefined method `name_en' for #Category::Translation:0x007f3ce896afd8>

It works fine in the console. When i type:
Category.friendly.find("men-shoes").name_en 
everything works fine.

I have no idea what the problem could be.

**Comment by shioyama** [comment]
Not enough information to debug this, please post a question on stackoverflow with more details.
