### ISSUE TITLE
Helper methods

### ISSUE THREAD

**Issue by dvodvo** [globalize/globalize-accessors#25]
Very handy gem. However it is not cleare if there are any helper methods, things that would allow to break on `attributes` and generate labels. As the number of languages increase and the number of fields increase, this exponential growth requires good layout.  I'm thinking along the lines of
```
Model.globalize_attribute_names.each do |attribute|
   div class="row"
      Model.globalize_attribute_names.each do |lang|
        div class="small-3 columns"
           %= lang %
           %= f.text_field lang
       /div
     end 
  /div
end
```
or i've missed some documentation!

**Comment by shioyama** [comment]
No there is no feature like this, but feel free to make a PR!
