### ISSUE TITLE
Dynamically Pass Locales

### ISSUE THREAD

**Issue by lukad03** [globalize/globalize-accessors#27]
I'm looking for a way to pass in locales from a controller or view when calling `globalize_attribute_names`. This way it will only return certain languages depending on the arguments passed. Any guidance on how I might achieve this through this gem or alternative means would be much appreciated. 

More info here: http://stackoverflow.com/questions/33313155/limit-globalize-accessor-locales-to-arguments-from-controller-view

**Comment by shioyama** [comment]
I answered the stackoverflow question, closing this.
